/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Hello10;

import org.junit.Test;
import static org.junit.Assert.*;
import com.mine.hello.*;

public class AppTest {
    @Test public void testAdd() {	
      assertEquals(5, Utils.add(2, 3));
    }
}
