/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Hello09;
import com.mine.hello.*;

public class App {
    public static void main(String[] args) {
        System.out.println(Utils.add(2, 3));
    }
}
